package com.bs.beststore.vo;

public class Address {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.AID
     *
     * @mbg.generated Sun Sep 02 14:34:44 CST 2018
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.APHONE
     *
     * @mbg.generated Sun Sep 02 14:34:44 CST 2018
     */
    private Long aphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.ACITY
     *
     * @mbg.generated Sun Sep 02 14:34:44 CST 2018
     */
    private String acity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.ALOCATION
     *
     * @mbg.generated Sun Sep 02 14:34:44 CST 2018
     */
    private String alocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.ACONSIGNEE
     *
     * @mbg.generated Sun Sep 02 14:34:44 CST 2018
     */
    private String aconsignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.ASTATUS
     *
     * @mbg.generated Sun Sep 02 14:34:44 CST 2018
     */
    private Integer astatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.HID
     *
     * @mbg.generated Sun Sep 02 14:34:44 CST 2018
     */
    private Integer hid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.AID
     *
     * @return the value of address.AID
     *
     * @mbg.generated Sun Sep 02 14:34:44 CST 2018
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.AID
     *
     * @param aid the value for address.AID
     *
     * @mbg.generated Sun Sep 02 14:34:44 CST 2018
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.APHONE
     *
     * @return the value of address.APHONE
     *
     * @mbg.generated Sun Sep 02 14:34:44 CST 2018
     */
    public Long getAphone() {
        return aphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.APHONE
     *
     * @param aphone the value for address.APHONE
     *
     * @mbg.generated Sun Sep 02 14:34:44 CST 2018
     */
    public void setAphone(Long aphone) {
        this.aphone = aphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.ACITY
     *
     * @return the value of address.ACITY
     *
     * @mbg.generated Sun Sep 02 14:34:44 CST 2018
     */
    public String getAcity() {
        return acity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.ACITY
     *
     * @param acity the value for address.ACITY
     *
     * @mbg.generated Sun Sep 02 14:34:44 CST 2018
     */
    public void setAcity(String acity) {
        this.acity = acity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.ALOCATION
     *
     * @return the value of address.ALOCATION
     *
     * @mbg.generated Sun Sep 02 14:34:44 CST 2018
     */
    public String getAlocation() {
        return alocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.ALOCATION
     *
     * @param alocation the value for address.ALOCATION
     *
     * @mbg.generated Sun Sep 02 14:34:44 CST 2018
     */
    public void setAlocation(String alocation) {
        this.alocation = alocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.ACONSIGNEE
     *
     * @return the value of address.ACONSIGNEE
     *
     * @mbg.generated Sun Sep 02 14:34:44 CST 2018
     */
    public String getAconsignee() {
        return aconsignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.ACONSIGNEE
     *
     * @param aconsignee the value for address.ACONSIGNEE
     *
     * @mbg.generated Sun Sep 02 14:34:44 CST 2018
     */
    public void setAconsignee(String aconsignee) {
        this.aconsignee = aconsignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.ASTATUS
     *
     * @return the value of address.ASTATUS
     *
     * @mbg.generated Sun Sep 02 14:34:44 CST 2018
     */
    public Integer getAstatus() {
        return astatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.ASTATUS
     *
     * @param astatus the value for address.ASTATUS
     *
     * @mbg.generated Sun Sep 02 14:34:44 CST 2018
     */
    public void setAstatus(Integer astatus) {
        this.astatus = astatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.HID
     *
     * @return the value of address.HID
     *
     * @mbg.generated Sun Sep 02 14:34:44 CST 2018
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.HID
     *
     * @param hid the value for address.HID
     *
     * @mbg.generated Sun Sep 02 14:34:44 CST 2018
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }
}