package com.bs.beststore.vo;

import java.util.Date;

/**
 * 博客表
 *bid：博客id	、btitle：博客标题、bdesc：博客描述、bphoto：图片路径
 *btime：发布时间、bstatus：博客的状态，0审核中，1发布中，2审核未通过、sid：商铺id
 */
public class Blog {
    private Integer bid;

    private String btitle;

    private String bdesc;

    private String bphoto;

    private Date btime;

    private Integer bstatus;

    private Integer sid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.BID
     *
     * @return the value of blog.BID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.BID
     *
     * @param bid the value for blog.BID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.BTITLE
     *
     * @return the value of blog.BTITLE
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public String getBtitle() {
        return btitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.BTITLE
     *
     * @param btitle the value for blog.BTITLE
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setBtitle(String btitle) {
        this.btitle = btitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.BDESC
     *
     * @return the value of blog.BDESC
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public String getBdesc() {
        return bdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.BDESC
     *
     * @param bdesc the value for blog.BDESC
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setBdesc(String bdesc) {
        this.bdesc = bdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.BPHOTO
     *
     * @return the value of blog.BPHOTO
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public String getBphoto() {
        return bphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.BPHOTO
     *
     * @param bphoto the value for blog.BPHOTO
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setBphoto(String bphoto) {
        this.bphoto = bphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.BTIME
     *
     * @return the value of blog.BTIME
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Date getBtime() {
        return btime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.BTIME
     *
     * @param btime the value for blog.BTIME
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setBtime(Date btime) {
        this.btime = btime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.BSTATUS
     *
     * @return the value of blog.BSTATUS
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getBstatus() {
        return bstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.BSTATUS
     *
     * @param bstatus the value for blog.BSTATUS
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setBstatus(Integer bstatus) {
        this.bstatus = bstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.SID
     *
     * @return the value of blog.SID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.SID
     *
     * @param sid the value for blog.SID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }
}