package com.bs.beststore.vo;

import java.util.Date;

public class Blog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.BID
     *
     * @mbg.generated Mon Aug 20 14:58:03 CST 2018
     */
    private Integer bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.BTITLE
     *
     * @mbg.generated Mon Aug 20 14:58:03 CST 2018
     */
    private String btitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.BDESC
     *
     * @mbg.generated Mon Aug 20 14:58:03 CST 2018
     */
    private String bdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.BPHOTO
     *
     * @mbg.generated Mon Aug 20 14:58:03 CST 2018
     */
    private String bphoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.BTIME
     *
     * @mbg.generated Mon Aug 20 14:58:03 CST 2018
     */
    private Date btime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.BSTATUS
     *
     * @mbg.generated Mon Aug 20 14:58:03 CST 2018
     */
    private Integer bstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.SID
     *
     * @mbg.generated Mon Aug 20 14:58:03 CST 2018
     */
    private Integer sid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.BID
     *
     * @return the value of blog.BID
     *
     * @mbg.generated Mon Aug 20 14:58:03 CST 2018
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.BID
     *
     * @param bid the value for blog.BID
     *
     * @mbg.generated Mon Aug 20 14:58:03 CST 2018
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.BTITLE
     *
     * @return the value of blog.BTITLE
     *
     * @mbg.generated Mon Aug 20 14:58:03 CST 2018
     */
    public String getBtitle() {
        return btitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.BTITLE
     *
     * @param btitle the value for blog.BTITLE
     *
     * @mbg.generated Mon Aug 20 14:58:03 CST 2018
     */
    public void setBtitle(String btitle) {
        this.btitle = btitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.BDESC
     *
     * @return the value of blog.BDESC
     *
     * @mbg.generated Mon Aug 20 14:58:03 CST 2018
     */
    public String getBdesc() {
        return bdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.BDESC
     *
     * @param bdesc the value for blog.BDESC
     *
     * @mbg.generated Mon Aug 20 14:58:03 CST 2018
     */
    public void setBdesc(String bdesc) {
        this.bdesc = bdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.BPHOTO
     *
     * @return the value of blog.BPHOTO
     *
     * @mbg.generated Mon Aug 20 14:58:03 CST 2018
     */
    public String getBphoto() {
        return bphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.BPHOTO
     *
     * @param bphoto the value for blog.BPHOTO
     *
     * @mbg.generated Mon Aug 20 14:58:03 CST 2018
     */
    public void setBphoto(String bphoto) {
        this.bphoto = bphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.BTIME
     *
     * @return the value of blog.BTIME
     *
     * @mbg.generated Mon Aug 20 14:58:03 CST 2018
     */
    public Date getBtime() {
        return btime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.BTIME
     *
     * @param btime the value for blog.BTIME
     *
     * @mbg.generated Mon Aug 20 14:58:03 CST 2018
     */
    public void setBtime(Date btime) {
        this.btime = btime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.BSTATUS
     *
     * @return the value of blog.BSTATUS
     *
     * @mbg.generated Mon Aug 20 14:58:03 CST 2018
     */
    public Integer getBstatus() {
        return bstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.BSTATUS
     *
     * @param bstatus the value for blog.BSTATUS
     *
     * @mbg.generated Mon Aug 20 14:58:03 CST 2018
     */
    public void setBstatus(Integer bstatus) {
        this.bstatus = bstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.SID
     *
     * @return the value of blog.SID
     *
     * @mbg.generated Mon Aug 20 14:58:03 CST 2018
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.SID
     *
     * @param sid the value for blog.SID
     *
     * @mbg.generated Mon Aug 20 14:58:03 CST 2018
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }
}