package com.bs.beststore.vo;

/**
 * 购物车表
 *cid：购物车id、cnum：数量、pid：图片id、gid：商品id、hid：购物信息id
 */
public class Cart {
    private Integer cid;

    private Integer cnum;

    private Integer pid;

    private Integer gid;

    private Integer hid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.CID
     *
     * @return the value of cart.CID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.CID
     *
     * @param cid the value for cart.CID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.CNUM
     *
     * @return the value of cart.CNUM
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getCnum() {
        return cnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.CNUM
     *
     * @param cnum the value for cart.CNUM
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setCnum(Integer cnum) {
        this.cnum = cnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.PID
     *
     * @return the value of cart.PID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.PID
     *
     * @param pid the value for cart.PID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.GID
     *
     * @return the value of cart.GID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.GID
     *
     * @param gid the value for cart.GID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.HID
     *
     * @return the value of cart.HID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.HID
     *
     * @param hid the value for cart.HID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }
}