package com.bs.beststore.vo;

/**
 *评论表
 *did：评价id、depict：评价描述、drank：评价等级、dphoto：图片路径，每张图片中间用英文逗号分隔、
 *gid：商品id、hid：用户id
 */
public class Discuss {
    private Integer did;

    private String depict;

    private Integer drank;

    private String dphoto;

    private Integer gid;

    private Integer hid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss.DID
     *
     * @return the value of discuss.DID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss.DID
     *
     * @param did the value for discuss.DID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss.DEPICT
     *
     * @return the value of discuss.DEPICT
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public String getDepict() {
        return depict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss.DEPICT
     *
     * @param depict the value for discuss.DEPICT
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setDepict(String depict) {
        this.depict = depict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss.DRANK
     *
     * @return the value of discuss.DRANK
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getDrank() {
        return drank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss.DRANK
     *
     * @param drank the value for discuss.DRANK
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setDrank(Integer drank) {
        this.drank = drank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss.DPHOTO
     *
     * @return the value of discuss.DPHOTO
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public String getDphoto() {
        return dphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss.DPHOTO
     *
     * @param dphoto the value for discuss.DPHOTO
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setDphoto(String dphoto) {
        this.dphoto = dphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss.GID
     *
     * @return the value of discuss.GID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss.GID
     *
     * @param gid the value for discuss.GID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss.HID
     *
     * @return the value of discuss.HID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss.HID
     *
     * @param hid the value for discuss.HID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }
}