package com.bs.beststore.vo;

public class Favorite {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.FID
     *
     * @mbg.generated Mon Aug 20 09:28:45 CST 2018
     */
    private Integer fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.GID
     *
     * @mbg.generated Mon Aug 20 09:28:45 CST 2018
     */
    private Integer gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.HID
     *
     * @mbg.generated Mon Aug 20 09:28:45 CST 2018
     */
    private Integer hid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.FID
     *
     * @return the value of favorite.FID
     *
     * @mbg.generated Mon Aug 20 09:28:45 CST 2018
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.FID
     *
     * @param fid the value for favorite.FID
     *
     * @mbg.generated Mon Aug 20 09:28:45 CST 2018
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.GID
     *
     * @return the value of favorite.GID
     *
     * @mbg.generated Mon Aug 20 09:28:45 CST 2018
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.GID
     *
     * @param gid the value for favorite.GID
     *
     * @mbg.generated Mon Aug 20 09:28:45 CST 2018
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.HID
     *
     * @return the value of favorite.HID
     *
     * @mbg.generated Mon Aug 20 09:28:45 CST 2018
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.HID
     *
     * @param hid the value for favorite.HID
     *
     * @mbg.generated Mon Aug 20 09:28:45 CST 2018
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }
}