package com.bs.beststore.vo;

/**
 * 收藏夹
 *fid：收藏夹id、gid：商品id、hid：用户id
 */
public class Favorite {
    private Integer fid;

    private Integer gid;

    private Integer hid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.FID
     *
     * @return the value of favorite.FID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.FID
     *
     * @param fid the value for favorite.FID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.GID
     *
     * @return the value of favorite.GID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.GID
     *
     * @param gid the value for favorite.GID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.HID
     *
     * @return the value of favorite.HID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.HID
     *
     * @param hid the value for favorite.HID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }
}