package com.bs.beststore.vo;

import java.util.Date;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.GID
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    private Integer gid;

    @Override
	public String toString() {
		return "Goods [gid=" + gid + ", gname=" + gname + ", glastprice=" + glastprice + ", gnowprice=" + gnowprice
				+ ", gdesc=" + gdesc + ", grade=" + grade + ", gpublish=" + gpublish + ", gnumber=" + gnumber
				+ ", gphotopic=" + gphotopic + ", tid=" + tid + ", sid=" + sid + ", gstatus=" + gstatus + "]";
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.GNAME
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    private String gname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.GLASTPRICE
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    private Double glastprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.GNOWPRICE
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    private Double gnowprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.GDESC
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    private String gdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.GRADE
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    private Double grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.GPUBLISH
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    private Date gpublish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.GNUMBER
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    private Integer gnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.GPHOTOPIC
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    private String gphotopic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.TID
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.SID
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.GSTATUS
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    private Integer gstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.GID
     *
     * @return the value of goods.GID
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.GID
     *
     * @param gid the value for goods.GID
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.GNAME
     *
     * @return the value of goods.GNAME
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public String getGname() {
        return gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.GNAME
     *
     * @param gname the value for goods.GNAME
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public void setGname(String gname) {
        this.gname = gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.GLASTPRICE
     *
     * @return the value of goods.GLASTPRICE
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public Double getGlastprice() {
        return glastprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.GLASTPRICE
     *
     * @param glastprice the value for goods.GLASTPRICE
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public void setGlastprice(Double glastprice) {
        this.glastprice = glastprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.GNOWPRICE
     *
     * @return the value of goods.GNOWPRICE
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public Double getGnowprice() {
        return gnowprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.GNOWPRICE
     *
     * @param gnowprice the value for goods.GNOWPRICE
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public void setGnowprice(Double gnowprice) {
        this.gnowprice = gnowprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.GDESC
     *
     * @return the value of goods.GDESC
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public String getGdesc() {
        return gdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.GDESC
     *
     * @param gdesc the value for goods.GDESC
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public void setGdesc(String gdesc) {
        this.gdesc = gdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.GRADE
     *
     * @return the value of goods.GRADE
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public Double getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.GRADE
     *
     * @param grade the value for goods.GRADE
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public void setGrade(Double grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.GPUBLISH
     *
     * @return the value of goods.GPUBLISH
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public Date getGpublish() {
        return gpublish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.GPUBLISH
     *
     * @param gpublish the value for goods.GPUBLISH
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public void setGpublish(Date gpublish) {
        this.gpublish = gpublish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.GNUMBER
     *
     * @return the value of goods.GNUMBER
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public Integer getGnumber() {
        return gnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.GNUMBER
     *
     * @param gnumber the value for goods.GNUMBER
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public void setGnumber(Integer gnumber) {
        this.gnumber = gnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.GPHOTOPIC
     *
     * @return the value of goods.GPHOTOPIC
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public String getGphotopic() {
        return gphotopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.GPHOTOPIC
     *
     * @param gphotopic the value for goods.GPHOTOPIC
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public void setGphotopic(String gphotopic) {
        this.gphotopic = gphotopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.TID
     *
     * @return the value of goods.TID
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.TID
     *
     * @param tid the value for goods.TID
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.SID
     *
     * @return the value of goods.SID
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.SID
     *
     * @param sid the value for goods.SID
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.GSTATUS
     *
     * @return the value of goods.GSTATUS
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public Integer getGstatus() {
        return gstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.GSTATUS
     *
     * @param gstatus the value for goods.GSTATUS
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public void setGstatus(Integer gstatus) {
        this.gstatus = gstatus;
    }
}