package com.bs.beststore.vo;

import java.util.Date;

/**
 * 用户表（包括管理员）
 *hid：用户id、hname：用户名，非空唯一、hpwd：密码，非空唯一，由用户名加密码组合加密存储到该字段、
 *hsex：性别，1为男，0为女、height：身高，单位cm、hweight：体重，单位为kg、hbirth：生日、
 *hidcard：身份证号码，非空唯一、hphone：注册手机号、hemail：邮箱地址、hphoto：头像图片路径、
 *hlimit：账号等级，0用户，1店铺，2超级管理员，3已经销毁
 */
public class Human {
    private Integer hid;

    private String hname;

    private String hpwd;

    private Integer hsex;

    private Integer height;

    private Double hweight;

    private Date hbirth;

    private Long hidcard;

    private Long hphone;

    private String hemail;

    private String hphoto;

    private Integer hlimit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column human.HID
     *
     * @return the value of human.HID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column human.HID
     *
     * @param hid the value for human.HID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column human.HNAME
     *
     * @return the value of human.HNAME
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public String getHname() {
        return hname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column human.HNAME
     *
     * @param hname the value for human.HNAME
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setHname(String hname) {
        this.hname = hname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column human.HPWD
     *
     * @return the value of human.HPWD
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public String getHpwd() {
        return hpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column human.HPWD
     *
     * @param hpwd the value for human.HPWD
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setHpwd(String hpwd) {
        this.hpwd = hpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column human.HSEX
     *
     * @return the value of human.HSEX
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getHsex() {
        return hsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column human.HSEX
     *
     * @param hsex the value for human.HSEX
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setHsex(Integer hsex) {
        this.hsex = hsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column human.HEIGHT
     *
     * @return the value of human.HEIGHT
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column human.HEIGHT
     *
     * @param height the value for human.HEIGHT
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column human.HWEIGHT
     *
     * @return the value of human.HWEIGHT
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Double getHweight() {
        return hweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column human.HWEIGHT
     *
     * @param hweight the value for human.HWEIGHT
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setHweight(Double hweight) {
        this.hweight = hweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column human.HBIRTH
     *
     * @return the value of human.HBIRTH
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Date getHbirth() {
        return hbirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column human.HBIRTH
     *
     * @param hbirth the value for human.HBIRTH
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setHbirth(Date hbirth) {
        this.hbirth = hbirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column human.HIDCARD
     *
     * @return the value of human.HIDCARD
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Long getHidcard() {
        return hidcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column human.HIDCARD
     *
     * @param hidcard the value for human.HIDCARD
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setHidcard(Long hidcard) {
        this.hidcard = hidcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column human.HPHONE
     *
     * @return the value of human.HPHONE
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Long getHphone() {
        return hphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column human.HPHONE
     *
     * @param hphone the value for human.HPHONE
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setHphone(Long hphone) {
        this.hphone = hphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column human.HEMAIL
     *
     * @return the value of human.HEMAIL
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public String getHemail() {
        return hemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column human.HEMAIL
     *
     * @param hemail the value for human.HEMAIL
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setHemail(String hemail) {
        this.hemail = hemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column human.HPHOTO
     *
     * @return the value of human.HPHOTO
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public String getHphoto() {
        return hphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column human.HPHOTO
     *
     * @param hphoto the value for human.HPHOTO
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setHphoto(String hphoto) {
        this.hphoto = hphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column human.HLIMIT
     *
     * @return the value of human.HLIMIT
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getHlimit() {
        return hlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column human.HLIMIT
     *
     * @param hlimit the value for human.HLIMIT
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setHlimit(Integer hlimit) {
        this.hlimit = hlimit;
    }
}