package com.bs.beststore.vo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class HumanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table human
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table human
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table human
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table human
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    public HumanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table human
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table human
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table human
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table human
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table human
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table human
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table human
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table human
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table human
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table human
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table human
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHidIsNull() {
            addCriterion("HID is null");
            return (Criteria) this;
        }

        public Criteria andHidIsNotNull() {
            addCriterion("HID is not null");
            return (Criteria) this;
        }

        public Criteria andHidEqualTo(Integer value) {
            addCriterion("HID =", value, "hid");
            return (Criteria) this;
        }

        public Criteria andHidNotEqualTo(Integer value) {
            addCriterion("HID <>", value, "hid");
            return (Criteria) this;
        }

        public Criteria andHidGreaterThan(Integer value) {
            addCriterion("HID >", value, "hid");
            return (Criteria) this;
        }

        public Criteria andHidGreaterThanOrEqualTo(Integer value) {
            addCriterion("HID >=", value, "hid");
            return (Criteria) this;
        }

        public Criteria andHidLessThan(Integer value) {
            addCriterion("HID <", value, "hid");
            return (Criteria) this;
        }

        public Criteria andHidLessThanOrEqualTo(Integer value) {
            addCriterion("HID <=", value, "hid");
            return (Criteria) this;
        }

        public Criteria andHidIn(List<Integer> values) {
            addCriterion("HID in", values, "hid");
            return (Criteria) this;
        }

        public Criteria andHidNotIn(List<Integer> values) {
            addCriterion("HID not in", values, "hid");
            return (Criteria) this;
        }

        public Criteria andHidBetween(Integer value1, Integer value2) {
            addCriterion("HID between", value1, value2, "hid");
            return (Criteria) this;
        }

        public Criteria andHidNotBetween(Integer value1, Integer value2) {
            addCriterion("HID not between", value1, value2, "hid");
            return (Criteria) this;
        }

        public Criteria andHnameIsNull() {
            addCriterion("HNAME is null");
            return (Criteria) this;
        }

        public Criteria andHnameIsNotNull() {
            addCriterion("HNAME is not null");
            return (Criteria) this;
        }

        public Criteria andHnameEqualTo(String value) {
            addCriterion("HNAME =", value, "hname");
            return (Criteria) this;
        }

        public Criteria andHnameNotEqualTo(String value) {
            addCriterion("HNAME <>", value, "hname");
            return (Criteria) this;
        }

        public Criteria andHnameGreaterThan(String value) {
            addCriterion("HNAME >", value, "hname");
            return (Criteria) this;
        }

        public Criteria andHnameGreaterThanOrEqualTo(String value) {
            addCriterion("HNAME >=", value, "hname");
            return (Criteria) this;
        }

        public Criteria andHnameLessThan(String value) {
            addCriterion("HNAME <", value, "hname");
            return (Criteria) this;
        }

        public Criteria andHnameLessThanOrEqualTo(String value) {
            addCriterion("HNAME <=", value, "hname");
            return (Criteria) this;
        }

        public Criteria andHnameLike(String value) {
            addCriterion("HNAME like", value, "hname");
            return (Criteria) this;
        }

        public Criteria andHnameNotLike(String value) {
            addCriterion("HNAME not like", value, "hname");
            return (Criteria) this;
        }

        public Criteria andHnameIn(List<String> values) {
            addCriterion("HNAME in", values, "hname");
            return (Criteria) this;
        }

        public Criteria andHnameNotIn(List<String> values) {
            addCriterion("HNAME not in", values, "hname");
            return (Criteria) this;
        }

        public Criteria andHnameBetween(String value1, String value2) {
            addCriterion("HNAME between", value1, value2, "hname");
            return (Criteria) this;
        }

        public Criteria andHnameNotBetween(String value1, String value2) {
            addCriterion("HNAME not between", value1, value2, "hname");
            return (Criteria) this;
        }

        public Criteria andHpwdIsNull() {
            addCriterion("HPWD is null");
            return (Criteria) this;
        }

        public Criteria andHpwdIsNotNull() {
            addCriterion("HPWD is not null");
            return (Criteria) this;
        }

        public Criteria andHpwdEqualTo(String value) {
            addCriterion("HPWD =", value, "hpwd");
            return (Criteria) this;
        }

        public Criteria andHpwdNotEqualTo(String value) {
            addCriterion("HPWD <>", value, "hpwd");
            return (Criteria) this;
        }

        public Criteria andHpwdGreaterThan(String value) {
            addCriterion("HPWD >", value, "hpwd");
            return (Criteria) this;
        }

        public Criteria andHpwdGreaterThanOrEqualTo(String value) {
            addCriterion("HPWD >=", value, "hpwd");
            return (Criteria) this;
        }

        public Criteria andHpwdLessThan(String value) {
            addCriterion("HPWD <", value, "hpwd");
            return (Criteria) this;
        }

        public Criteria andHpwdLessThanOrEqualTo(String value) {
            addCriterion("HPWD <=", value, "hpwd");
            return (Criteria) this;
        }

        public Criteria andHpwdLike(String value) {
            addCriterion("HPWD like", value, "hpwd");
            return (Criteria) this;
        }

        public Criteria andHpwdNotLike(String value) {
            addCriterion("HPWD not like", value, "hpwd");
            return (Criteria) this;
        }

        public Criteria andHpwdIn(List<String> values) {
            addCriterion("HPWD in", values, "hpwd");
            return (Criteria) this;
        }

        public Criteria andHpwdNotIn(List<String> values) {
            addCriterion("HPWD not in", values, "hpwd");
            return (Criteria) this;
        }

        public Criteria andHpwdBetween(String value1, String value2) {
            addCriterion("HPWD between", value1, value2, "hpwd");
            return (Criteria) this;
        }

        public Criteria andHpwdNotBetween(String value1, String value2) {
            addCriterion("HPWD not between", value1, value2, "hpwd");
            return (Criteria) this;
        }

        public Criteria andHsexIsNull() {
            addCriterion("HSEX is null");
            return (Criteria) this;
        }

        public Criteria andHsexIsNotNull() {
            addCriterion("HSEX is not null");
            return (Criteria) this;
        }

        public Criteria andHsexEqualTo(Integer value) {
            addCriterion("HSEX =", value, "hsex");
            return (Criteria) this;
        }

        public Criteria andHsexNotEqualTo(Integer value) {
            addCriterion("HSEX <>", value, "hsex");
            return (Criteria) this;
        }

        public Criteria andHsexGreaterThan(Integer value) {
            addCriterion("HSEX >", value, "hsex");
            return (Criteria) this;
        }

        public Criteria andHsexGreaterThanOrEqualTo(Integer value) {
            addCriterion("HSEX >=", value, "hsex");
            return (Criteria) this;
        }

        public Criteria andHsexLessThan(Integer value) {
            addCriterion("HSEX <", value, "hsex");
            return (Criteria) this;
        }

        public Criteria andHsexLessThanOrEqualTo(Integer value) {
            addCriterion("HSEX <=", value, "hsex");
            return (Criteria) this;
        }

        public Criteria andHsexIn(List<Integer> values) {
            addCriterion("HSEX in", values, "hsex");
            return (Criteria) this;
        }

        public Criteria andHsexNotIn(List<Integer> values) {
            addCriterion("HSEX not in", values, "hsex");
            return (Criteria) this;
        }

        public Criteria andHsexBetween(Integer value1, Integer value2) {
            addCriterion("HSEX between", value1, value2, "hsex");
            return (Criteria) this;
        }

        public Criteria andHsexNotBetween(Integer value1, Integer value2) {
            addCriterion("HSEX not between", value1, value2, "hsex");
            return (Criteria) this;
        }

        public Criteria andHeightIsNull() {
            addCriterion("HEIGHT is null");
            return (Criteria) this;
        }

        public Criteria andHeightIsNotNull() {
            addCriterion("HEIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andHeightEqualTo(Integer value) {
            addCriterion("HEIGHT =", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotEqualTo(Integer value) {
            addCriterion("HEIGHT <>", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThan(Integer value) {
            addCriterion("HEIGHT >", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("HEIGHT >=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThan(Integer value) {
            addCriterion("HEIGHT <", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThanOrEqualTo(Integer value) {
            addCriterion("HEIGHT <=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightIn(List<Integer> values) {
            addCriterion("HEIGHT in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotIn(List<Integer> values) {
            addCriterion("HEIGHT not in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightBetween(Integer value1, Integer value2) {
            addCriterion("HEIGHT between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotBetween(Integer value1, Integer value2) {
            addCriterion("HEIGHT not between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andHweightIsNull() {
            addCriterion("HWEIGHT is null");
            return (Criteria) this;
        }

        public Criteria andHweightIsNotNull() {
            addCriterion("HWEIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andHweightEqualTo(Double value) {
            addCriterion("HWEIGHT =", value, "hweight");
            return (Criteria) this;
        }

        public Criteria andHweightNotEqualTo(Double value) {
            addCriterion("HWEIGHT <>", value, "hweight");
            return (Criteria) this;
        }

        public Criteria andHweightGreaterThan(Double value) {
            addCriterion("HWEIGHT >", value, "hweight");
            return (Criteria) this;
        }

        public Criteria andHweightGreaterThanOrEqualTo(Double value) {
            addCriterion("HWEIGHT >=", value, "hweight");
            return (Criteria) this;
        }

        public Criteria andHweightLessThan(Double value) {
            addCriterion("HWEIGHT <", value, "hweight");
            return (Criteria) this;
        }

        public Criteria andHweightLessThanOrEqualTo(Double value) {
            addCriterion("HWEIGHT <=", value, "hweight");
            return (Criteria) this;
        }

        public Criteria andHweightIn(List<Double> values) {
            addCriterion("HWEIGHT in", values, "hweight");
            return (Criteria) this;
        }

        public Criteria andHweightNotIn(List<Double> values) {
            addCriterion("HWEIGHT not in", values, "hweight");
            return (Criteria) this;
        }

        public Criteria andHweightBetween(Double value1, Double value2) {
            addCriterion("HWEIGHT between", value1, value2, "hweight");
            return (Criteria) this;
        }

        public Criteria andHweightNotBetween(Double value1, Double value2) {
            addCriterion("HWEIGHT not between", value1, value2, "hweight");
            return (Criteria) this;
        }

        public Criteria andHbirthIsNull() {
            addCriterion("HBIRTH is null");
            return (Criteria) this;
        }

        public Criteria andHbirthIsNotNull() {
            addCriterion("HBIRTH is not null");
            return (Criteria) this;
        }

        public Criteria andHbirthEqualTo(Date value) {
            addCriterion("HBIRTH =", value, "hbirth");
            return (Criteria) this;
        }

        public Criteria andHbirthNotEqualTo(Date value) {
            addCriterion("HBIRTH <>", value, "hbirth");
            return (Criteria) this;
        }

        public Criteria andHbirthGreaterThan(Date value) {
            addCriterion("HBIRTH >", value, "hbirth");
            return (Criteria) this;
        }

        public Criteria andHbirthGreaterThanOrEqualTo(Date value) {
            addCriterion("HBIRTH >=", value, "hbirth");
            return (Criteria) this;
        }

        public Criteria andHbirthLessThan(Date value) {
            addCriterion("HBIRTH <", value, "hbirth");
            return (Criteria) this;
        }

        public Criteria andHbirthLessThanOrEqualTo(Date value) {
            addCriterion("HBIRTH <=", value, "hbirth");
            return (Criteria) this;
        }

        public Criteria andHbirthIn(List<Date> values) {
            addCriterion("HBIRTH in", values, "hbirth");
            return (Criteria) this;
        }

        public Criteria andHbirthNotIn(List<Date> values) {
            addCriterion("HBIRTH not in", values, "hbirth");
            return (Criteria) this;
        }

        public Criteria andHbirthBetween(Date value1, Date value2) {
            addCriterion("HBIRTH between", value1, value2, "hbirth");
            return (Criteria) this;
        }

        public Criteria andHbirthNotBetween(Date value1, Date value2) {
            addCriterion("HBIRTH not between", value1, value2, "hbirth");
            return (Criteria) this;
        }

        public Criteria andHidcardIsNull() {
            addCriterion("HIDCARD is null");
            return (Criteria) this;
        }

        public Criteria andHidcardIsNotNull() {
            addCriterion("HIDCARD is not null");
            return (Criteria) this;
        }

        public Criteria andHidcardEqualTo(Long value) {
            addCriterion("HIDCARD =", value, "hidcard");
            return (Criteria) this;
        }

        public Criteria andHidcardNotEqualTo(Long value) {
            addCriterion("HIDCARD <>", value, "hidcard");
            return (Criteria) this;
        }

        public Criteria andHidcardGreaterThan(Long value) {
            addCriterion("HIDCARD >", value, "hidcard");
            return (Criteria) this;
        }

        public Criteria andHidcardGreaterThanOrEqualTo(Long value) {
            addCriterion("HIDCARD >=", value, "hidcard");
            return (Criteria) this;
        }

        public Criteria andHidcardLessThan(Long value) {
            addCriterion("HIDCARD <", value, "hidcard");
            return (Criteria) this;
        }

        public Criteria andHidcardLessThanOrEqualTo(Long value) {
            addCriterion("HIDCARD <=", value, "hidcard");
            return (Criteria) this;
        }

        public Criteria andHidcardIn(List<Long> values) {
            addCriterion("HIDCARD in", values, "hidcard");
            return (Criteria) this;
        }

        public Criteria andHidcardNotIn(List<Long> values) {
            addCriterion("HIDCARD not in", values, "hidcard");
            return (Criteria) this;
        }

        public Criteria andHidcardBetween(Long value1, Long value2) {
            addCriterion("HIDCARD between", value1, value2, "hidcard");
            return (Criteria) this;
        }

        public Criteria andHidcardNotBetween(Long value1, Long value2) {
            addCriterion("HIDCARD not between", value1, value2, "hidcard");
            return (Criteria) this;
        }

        public Criteria andHphoneIsNull() {
            addCriterion("HPHONE is null");
            return (Criteria) this;
        }

        public Criteria andHphoneIsNotNull() {
            addCriterion("HPHONE is not null");
            return (Criteria) this;
        }

        public Criteria andHphoneEqualTo(Long value) {
            addCriterion("HPHONE =", value, "hphone");
            return (Criteria) this;
        }

        public Criteria andHphoneNotEqualTo(Long value) {
            addCriterion("HPHONE <>", value, "hphone");
            return (Criteria) this;
        }

        public Criteria andHphoneGreaterThan(Long value) {
            addCriterion("HPHONE >", value, "hphone");
            return (Criteria) this;
        }

        public Criteria andHphoneGreaterThanOrEqualTo(Long value) {
            addCriterion("HPHONE >=", value, "hphone");
            return (Criteria) this;
        }

        public Criteria andHphoneLessThan(Long value) {
            addCriterion("HPHONE <", value, "hphone");
            return (Criteria) this;
        }

        public Criteria andHphoneLessThanOrEqualTo(Long value) {
            addCriterion("HPHONE <=", value, "hphone");
            return (Criteria) this;
        }

        public Criteria andHphoneIn(List<Long> values) {
            addCriterion("HPHONE in", values, "hphone");
            return (Criteria) this;
        }

        public Criteria andHphoneNotIn(List<Long> values) {
            addCriterion("HPHONE not in", values, "hphone");
            return (Criteria) this;
        }

        public Criteria andHphoneBetween(Long value1, Long value2) {
            addCriterion("HPHONE between", value1, value2, "hphone");
            return (Criteria) this;
        }

        public Criteria andHphoneNotBetween(Long value1, Long value2) {
            addCriterion("HPHONE not between", value1, value2, "hphone");
            return (Criteria) this;
        }

        public Criteria andHemailIsNull() {
            addCriterion("HEMAIL is null");
            return (Criteria) this;
        }

        public Criteria andHemailIsNotNull() {
            addCriterion("HEMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andHemailEqualTo(String value) {
            addCriterion("HEMAIL =", value, "hemail");
            return (Criteria) this;
        }

        public Criteria andHemailNotEqualTo(String value) {
            addCriterion("HEMAIL <>", value, "hemail");
            return (Criteria) this;
        }

        public Criteria andHemailGreaterThan(String value) {
            addCriterion("HEMAIL >", value, "hemail");
            return (Criteria) this;
        }

        public Criteria andHemailGreaterThanOrEqualTo(String value) {
            addCriterion("HEMAIL >=", value, "hemail");
            return (Criteria) this;
        }

        public Criteria andHemailLessThan(String value) {
            addCriterion("HEMAIL <", value, "hemail");
            return (Criteria) this;
        }

        public Criteria andHemailLessThanOrEqualTo(String value) {
            addCriterion("HEMAIL <=", value, "hemail");
            return (Criteria) this;
        }

        public Criteria andHemailLike(String value) {
            addCriterion("HEMAIL like", value, "hemail");
            return (Criteria) this;
        }

        public Criteria andHemailNotLike(String value) {
            addCriterion("HEMAIL not like", value, "hemail");
            return (Criteria) this;
        }

        public Criteria andHemailIn(List<String> values) {
            addCriterion("HEMAIL in", values, "hemail");
            return (Criteria) this;
        }

        public Criteria andHemailNotIn(List<String> values) {
            addCriterion("HEMAIL not in", values, "hemail");
            return (Criteria) this;
        }

        public Criteria andHemailBetween(String value1, String value2) {
            addCriterion("HEMAIL between", value1, value2, "hemail");
            return (Criteria) this;
        }

        public Criteria andHemailNotBetween(String value1, String value2) {
            addCriterion("HEMAIL not between", value1, value2, "hemail");
            return (Criteria) this;
        }

        public Criteria andHphotoIsNull() {
            addCriterion("HPHOTO is null");
            return (Criteria) this;
        }

        public Criteria andHphotoIsNotNull() {
            addCriterion("HPHOTO is not null");
            return (Criteria) this;
        }

        public Criteria andHphotoEqualTo(String value) {
            addCriterion("HPHOTO =", value, "hphoto");
            return (Criteria) this;
        }

        public Criteria andHphotoNotEqualTo(String value) {
            addCriterion("HPHOTO <>", value, "hphoto");
            return (Criteria) this;
        }

        public Criteria andHphotoGreaterThan(String value) {
            addCriterion("HPHOTO >", value, "hphoto");
            return (Criteria) this;
        }

        public Criteria andHphotoGreaterThanOrEqualTo(String value) {
            addCriterion("HPHOTO >=", value, "hphoto");
            return (Criteria) this;
        }

        public Criteria andHphotoLessThan(String value) {
            addCriterion("HPHOTO <", value, "hphoto");
            return (Criteria) this;
        }

        public Criteria andHphotoLessThanOrEqualTo(String value) {
            addCriterion("HPHOTO <=", value, "hphoto");
            return (Criteria) this;
        }

        public Criteria andHphotoLike(String value) {
            addCriterion("HPHOTO like", value, "hphoto");
            return (Criteria) this;
        }

        public Criteria andHphotoNotLike(String value) {
            addCriterion("HPHOTO not like", value, "hphoto");
            return (Criteria) this;
        }

        public Criteria andHphotoIn(List<String> values) {
            addCriterion("HPHOTO in", values, "hphoto");
            return (Criteria) this;
        }

        public Criteria andHphotoNotIn(List<String> values) {
            addCriterion("HPHOTO not in", values, "hphoto");
            return (Criteria) this;
        }

        public Criteria andHphotoBetween(String value1, String value2) {
            addCriterion("HPHOTO between", value1, value2, "hphoto");
            return (Criteria) this;
        }

        public Criteria andHphotoNotBetween(String value1, String value2) {
            addCriterion("HPHOTO not between", value1, value2, "hphoto");
            return (Criteria) this;
        }

        public Criteria andHlimitIsNull() {
            addCriterion("HLIMIT is null");
            return (Criteria) this;
        }

        public Criteria andHlimitIsNotNull() {
            addCriterion("HLIMIT is not null");
            return (Criteria) this;
        }

        public Criteria andHlimitEqualTo(Integer value) {
            addCriterion("HLIMIT =", value, "hlimit");
            return (Criteria) this;
        }

        public Criteria andHlimitNotEqualTo(Integer value) {
            addCriterion("HLIMIT <>", value, "hlimit");
            return (Criteria) this;
        }

        public Criteria andHlimitGreaterThan(Integer value) {
            addCriterion("HLIMIT >", value, "hlimit");
            return (Criteria) this;
        }

        public Criteria andHlimitGreaterThanOrEqualTo(Integer value) {
            addCriterion("HLIMIT >=", value, "hlimit");
            return (Criteria) this;
        }

        public Criteria andHlimitLessThan(Integer value) {
            addCriterion("HLIMIT <", value, "hlimit");
            return (Criteria) this;
        }

        public Criteria andHlimitLessThanOrEqualTo(Integer value) {
            addCriterion("HLIMIT <=", value, "hlimit");
            return (Criteria) this;
        }

        public Criteria andHlimitIn(List<Integer> values) {
            addCriterion("HLIMIT in", values, "hlimit");
            return (Criteria) this;
        }

        public Criteria andHlimitNotIn(List<Integer> values) {
            addCriterion("HLIMIT not in", values, "hlimit");
            return (Criteria) this;
        }

        public Criteria andHlimitBetween(Integer value1, Integer value2) {
            addCriterion("HLIMIT between", value1, value2, "hlimit");
            return (Criteria) this;
        }

        public Criteria andHlimitNotBetween(Integer value1, Integer value2) {
            addCriterion("HLIMIT not between", value1, value2, "hlimit");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table human
     *
     * @mbg.generated do_not_delete_during_merge Thu Aug 30 11:45:05 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table human
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}