package com.bs.beststore.vo;

public class Ordersdetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordersdetail.ODID
     *
     * @mbg.generated Fri Aug 31 20:36:08 CST 2018
     */
    private Integer odid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordersdetail.GPRICE
     *
     * @mbg.generated Fri Aug 31 20:36:08 CST 2018
     */
    private Double gprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordersdetail.OID
     *
     * @mbg.generated Fri Aug 31 20:36:08 CST 2018
     */
    private Integer oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordersdetail.GID
     *
     * @mbg.generated Fri Aug 31 20:36:08 CST 2018
     */
    private Integer gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordersdetail.NUM
     *
     * @mbg.generated Fri Aug 31 20:36:08 CST 2018
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordersdetail.ODSTATUS
     *
     * @mbg.generated Fri Aug 31 20:36:08 CST 2018
     */
    private Integer odstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordersdetail.ODID
     *
     * @return the value of ordersdetail.ODID
     *
     * @mbg.generated Fri Aug 31 20:36:08 CST 2018
     */
    public Integer getOdid() {
        return odid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordersdetail.ODID
     *
     * @param odid the value for ordersdetail.ODID
     *
     * @mbg.generated Fri Aug 31 20:36:08 CST 2018
     */
    public void setOdid(Integer odid) {
        this.odid = odid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordersdetail.GPRICE
     *
     * @return the value of ordersdetail.GPRICE
     *
     * @mbg.generated Fri Aug 31 20:36:08 CST 2018
     */
    public Double getGprice() {
        return gprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordersdetail.GPRICE
     *
     * @param gprice the value for ordersdetail.GPRICE
     *
     * @mbg.generated Fri Aug 31 20:36:08 CST 2018
     */
    public void setGprice(Double gprice) {
        this.gprice = gprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordersdetail.OID
     *
     * @return the value of ordersdetail.OID
     *
     * @mbg.generated Fri Aug 31 20:36:08 CST 2018
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordersdetail.OID
     *
     * @param oid the value for ordersdetail.OID
     *
     * @mbg.generated Fri Aug 31 20:36:08 CST 2018
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordersdetail.GID
     *
     * @return the value of ordersdetail.GID
     *
     * @mbg.generated Fri Aug 31 20:36:08 CST 2018
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordersdetail.GID
     *
     * @param gid the value for ordersdetail.GID
     *
     * @mbg.generated Fri Aug 31 20:36:08 CST 2018
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordersdetail.NUM
     *
     * @return the value of ordersdetail.NUM
     *
     * @mbg.generated Fri Aug 31 20:36:08 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordersdetail.NUM
     *
     * @param num the value for ordersdetail.NUM
     *
     * @mbg.generated Fri Aug 31 20:36:08 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordersdetail.ODSTATUS
     *
     * @return the value of ordersdetail.ODSTATUS
     *
     * @mbg.generated Fri Aug 31 20:36:08 CST 2018
     */
    public Integer getOdstatus() {
        return odstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordersdetail.ODSTATUS
     *
     * @param odstatus the value for ordersdetail.ODSTATUS
     *
     * @mbg.generated Fri Aug 31 20:36:08 CST 2018
     */
    public void setOdstatus(Integer odstatus) {
        this.odstatus = odstatus;
    }
}