package com.bs.beststore.vo;

public class Ordersreturn {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordersreturn.ORID
     *
     * @mbg.generated Thu Aug 30 11:45:06 CST 2018
     */
    private Integer orid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordersreturn.ORSERVICE
     *
     * @mbg.generated Thu Aug 30 11:45:06 CST 2018
     */
    private Integer orservice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordersreturn.ORSTATUS
     *
     * @mbg.generated Thu Aug 30 11:45:06 CST 2018
     */
    private Integer orstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordersreturn.OREASON
     *
     * @mbg.generated Thu Aug 30 11:45:06 CST 2018
     */
    private Integer oreason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordersreturn.ORDESC
     *
     * @mbg.generated Thu Aug 30 11:45:06 CST 2018
     */
    private String ordesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordersreturn.ORPHOTO
     *
     * @mbg.generated Thu Aug 30 11:45:06 CST 2018
     */
    private String orphoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordersreturn.ORTYPE
     *
     * @mbg.generated Thu Aug 30 11:45:06 CST 2018
     */
    private Integer ortype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordersreturn.OID
     *
     * @mbg.generated Thu Aug 30 11:45:06 CST 2018
     */
    private Integer oid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordersreturn.ORID
     *
     * @return the value of ordersreturn.ORID
     *
     * @mbg.generated Thu Aug 30 11:45:06 CST 2018
     */
    public Integer getOrid() {
        return orid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordersreturn.ORID
     *
     * @param orid the value for ordersreturn.ORID
     *
     * @mbg.generated Thu Aug 30 11:45:06 CST 2018
     */
    public void setOrid(Integer orid) {
        this.orid = orid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordersreturn.ORSERVICE
     *
     * @return the value of ordersreturn.ORSERVICE
     *
     * @mbg.generated Thu Aug 30 11:45:06 CST 2018
     */
    public Integer getOrservice() {
        return orservice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordersreturn.ORSERVICE
     *
     * @param orservice the value for ordersreturn.ORSERVICE
     *
     * @mbg.generated Thu Aug 30 11:45:06 CST 2018
     */
    public void setOrservice(Integer orservice) {
        this.orservice = orservice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordersreturn.ORSTATUS
     *
     * @return the value of ordersreturn.ORSTATUS
     *
     * @mbg.generated Thu Aug 30 11:45:06 CST 2018
     */
    public Integer getOrstatus() {
        return orstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordersreturn.ORSTATUS
     *
     * @param orstatus the value for ordersreturn.ORSTATUS
     *
     * @mbg.generated Thu Aug 30 11:45:06 CST 2018
     */
    public void setOrstatus(Integer orstatus) {
        this.orstatus = orstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordersreturn.OREASON
     *
     * @return the value of ordersreturn.OREASON
     *
     * @mbg.generated Thu Aug 30 11:45:06 CST 2018
     */
    public Integer getOreason() {
        return oreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordersreturn.OREASON
     *
     * @param oreason the value for ordersreturn.OREASON
     *
     * @mbg.generated Thu Aug 30 11:45:06 CST 2018
     */
    public void setOreason(Integer oreason) {
        this.oreason = oreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordersreturn.ORDESC
     *
     * @return the value of ordersreturn.ORDESC
     *
     * @mbg.generated Thu Aug 30 11:45:06 CST 2018
     */
    public String getOrdesc() {
        return ordesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordersreturn.ORDESC
     *
     * @param ordesc the value for ordersreturn.ORDESC
     *
     * @mbg.generated Thu Aug 30 11:45:06 CST 2018
     */
    public void setOrdesc(String ordesc) {
        this.ordesc = ordesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordersreturn.ORPHOTO
     *
     * @return the value of ordersreturn.ORPHOTO
     *
     * @mbg.generated Thu Aug 30 11:45:06 CST 2018
     */
    public String getOrphoto() {
        return orphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordersreturn.ORPHOTO
     *
     * @param orphoto the value for ordersreturn.ORPHOTO
     *
     * @mbg.generated Thu Aug 30 11:45:06 CST 2018
     */
    public void setOrphoto(String orphoto) {
        this.orphoto = orphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordersreturn.ORTYPE
     *
     * @return the value of ordersreturn.ORTYPE
     *
     * @mbg.generated Thu Aug 30 11:45:06 CST 2018
     */
    public Integer getOrtype() {
        return ortype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordersreturn.ORTYPE
     *
     * @param ortype the value for ordersreturn.ORTYPE
     *
     * @mbg.generated Thu Aug 30 11:45:06 CST 2018
     */
    public void setOrtype(Integer ortype) {
        this.ortype = ortype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordersreturn.OID
     *
     * @return the value of ordersreturn.OID
     *
     * @mbg.generated Thu Aug 30 11:45:06 CST 2018
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordersreturn.OID
     *
     * @param oid the value for ordersreturn.OID
     *
     * @mbg.generated Thu Aug 30 11:45:06 CST 2018
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }
}