package com.bs.beststore.vo;

import java.util.Date;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.OID
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    private Integer oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.OTIME
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    private Date otime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.OPAYTIME
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    private Date opaytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ODEALTIME
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    private Date odealtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.OSTATUS
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    private Integer ostatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.AID
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.HID
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    private Integer hid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.OLASTPRICE
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    private Double olastprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ONOWPRICE
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    private Double onowprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.OID
     *
     * @return the value of orders.OID
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.OID
     *
     * @param oid the value for orders.OID
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.OTIME
     *
     * @return the value of orders.OTIME
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    public Date getOtime() {
        return otime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.OTIME
     *
     * @param otime the value for orders.OTIME
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    public void setOtime(Date otime) {
        this.otime = otime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.OPAYTIME
     *
     * @return the value of orders.OPAYTIME
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    public Date getOpaytime() {
        return opaytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.OPAYTIME
     *
     * @param opaytime the value for orders.OPAYTIME
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    public void setOpaytime(Date opaytime) {
        this.opaytime = opaytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ODEALTIME
     *
     * @return the value of orders.ODEALTIME
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    public Date getOdealtime() {
        return odealtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ODEALTIME
     *
     * @param odealtime the value for orders.ODEALTIME
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    public void setOdealtime(Date odealtime) {
        this.odealtime = odealtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.OSTATUS
     *
     * @return the value of orders.OSTATUS
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    public Integer getOstatus() {
        return ostatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.OSTATUS
     *
     * @param ostatus the value for orders.OSTATUS
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    public void setOstatus(Integer ostatus) {
        this.ostatus = ostatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.AID
     *
     * @return the value of orders.AID
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.AID
     *
     * @param aid the value for orders.AID
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.HID
     *
     * @return the value of orders.HID
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.HID
     *
     * @param hid the value for orders.HID
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.OLASTPRICE
     *
     * @return the value of orders.OLASTPRICE
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    public Double getOlastprice() {
        return olastprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.OLASTPRICE
     *
     * @param olastprice the value for orders.OLASTPRICE
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    public void setOlastprice(Double olastprice) {
        this.olastprice = olastprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ONOWPRICE
     *
     * @return the value of orders.ONOWPRICE
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    public Double getOnowprice() {
        return onowprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ONOWPRICE
     *
     * @param onowprice the value for orders.ONOWPRICE
     *
     * @mbg.generated Thu Aug 30 11:45:05 CST 2018
     */
    public void setOnowprice(Double onowprice) {
        this.onowprice = onowprice;
    }
}