package com.bs.beststore.vo;

/**
 * 订单详情表
 *odid：订单详情id、oid：订单id、gid：商品id、pid：商品图片id、num：商品数量
 */
public class Ordersdetail {
    private Integer odid;

    private Integer oid;

    private Integer gid;

    private Integer pid;

    private Integer num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordersdetail.ODID
     *
     * @return the value of ordersdetail.ODID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getOdid() {
        return odid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordersdetail.ODID
     *
     * @param odid the value for ordersdetail.ODID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setOdid(Integer odid) {
        this.odid = odid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordersdetail.OID
     *
     * @return the value of ordersdetail.OID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordersdetail.OID
     *
     * @param oid the value for ordersdetail.OID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordersdetail.GID
     *
     * @return the value of ordersdetail.GID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordersdetail.GID
     *
     * @param gid the value for ordersdetail.GID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordersdetail.PID
     *
     * @return the value of ordersdetail.PID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordersdetail.PID
     *
     * @param pid the value for ordersdetail.PID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordersdetail.NUM
     *
     * @return the value of ordersdetail.NUM
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordersdetail.NUM
     *
     * @param num the value for ordersdetail.NUM
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }
}