package com.bs.beststore.vo;

import java.util.Date;

/**
 * 订单表
 *oid：订单id、otime：提交订单时间、ostatus：付款状态，1付款，0为付款、
 *ostate：订单状态，1可见，0不可见、aid：地址id、hid：用户id、
 *olastprice：总原价、onowprice：总现价（优惠后的价格）
 */
public class Orders {
    private Integer oid;

    private Date otime;

    private Integer ostatus;

    private Integer ostate;

    private Integer aid;

    private Integer hid;

    private Double olastprice;

    private Double onowprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.OID
     *
     * @return the value of orders.OID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.OID
     *
     * @param oid the value for orders.OID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.OTIME
     *
     * @return the value of orders.OTIME
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Date getOtime() {
        return otime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.OTIME
     *
     * @param otime the value for orders.OTIME
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setOtime(Date otime) {
        this.otime = otime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.OSTATUS
     *
     * @return the value of orders.OSTATUS
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getOstatus() {
        return ostatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.OSTATUS
     *
     * @param ostatus the value for orders.OSTATUS
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setOstatus(Integer ostatus) {
        this.ostatus = ostatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.OSTATE
     *
     * @return the value of orders.OSTATE
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getOstate() {
        return ostate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.OSTATE
     *
     * @param ostate the value for orders.OSTATE
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setOstate(Integer ostate) {
        this.ostate = ostate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.AID
     *
     * @return the value of orders.AID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.AID
     *
     * @param aid the value for orders.AID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.HID
     *
     * @return the value of orders.HID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.HID
     *
     * @param hid the value for orders.HID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.OLASTPRICE
     *
     * @return the value of orders.OLASTPRICE
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Double getOlastprice() {
        return olastprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.OLASTPRICE
     *
     * @param olastprice the value for orders.OLASTPRICE
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setOlastprice(Double olastprice) {
        this.olastprice = olastprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ONOWPRICE
     *
     * @return the value of orders.ONOWPRICE
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Double getOnowprice() {
        return onowprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ONOWPRICE
     *
     * @param onowprice the value for orders.ONOWPRICE
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setOnowprice(Double onowprice) {
        this.onowprice = onowprice;
    }
}