package com.bs.beststore.vo;

public class Photo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.PID
     *
     * @mbg.generated Mon Aug 20 14:58:04 CST 2018
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.PNUM
     *
     * @mbg.generated Mon Aug 20 14:58:04 CST 2018
     */
    private Integer pnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.PSIZE
     *
     * @mbg.generated Mon Aug 20 14:58:04 CST 2018
     */
    private String psize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.PCOLOR
     *
     * @mbg.generated Mon Aug 20 14:58:04 CST 2018
     */
    private String pcolor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.PIC
     *
     * @mbg.generated Mon Aug 20 14:58:04 CST 2018
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.GID
     *
     * @mbg.generated Mon Aug 20 14:58:04 CST 2018
     */
    private Integer gid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.PID
     *
     * @return the value of photo.PID
     *
     * @mbg.generated Mon Aug 20 14:58:04 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.PID
     *
     * @param pid the value for photo.PID
     *
     * @mbg.generated Mon Aug 20 14:58:04 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.PNUM
     *
     * @return the value of photo.PNUM
     *
     * @mbg.generated Mon Aug 20 14:58:04 CST 2018
     */
    public Integer getPnum() {
        return pnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.PNUM
     *
     * @param pnum the value for photo.PNUM
     *
     * @mbg.generated Mon Aug 20 14:58:04 CST 2018
     */
    public void setPnum(Integer pnum) {
        this.pnum = pnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.PSIZE
     *
     * @return the value of photo.PSIZE
     *
     * @mbg.generated Mon Aug 20 14:58:04 CST 2018
     */
    public String getPsize() {
        return psize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.PSIZE
     *
     * @param psize the value for photo.PSIZE
     *
     * @mbg.generated Mon Aug 20 14:58:04 CST 2018
     */
    public void setPsize(String psize) {
        this.psize = psize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.PCOLOR
     *
     * @return the value of photo.PCOLOR
     *
     * @mbg.generated Mon Aug 20 14:58:04 CST 2018
     */
    public String getPcolor() {
        return pcolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.PCOLOR
     *
     * @param pcolor the value for photo.PCOLOR
     *
     * @mbg.generated Mon Aug 20 14:58:04 CST 2018
     */
    public void setPcolor(String pcolor) {
        this.pcolor = pcolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.PIC
     *
     * @return the value of photo.PIC
     *
     * @mbg.generated Mon Aug 20 14:58:04 CST 2018
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.PIC
     *
     * @param pic the value for photo.PIC
     *
     * @mbg.generated Mon Aug 20 14:58:04 CST 2018
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.GID
     *
     * @return the value of photo.GID
     *
     * @mbg.generated Mon Aug 20 14:58:04 CST 2018
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.GID
     *
     * @param gid the value for photo.GID
     *
     * @mbg.generated Mon Aug 20 14:58:04 CST 2018
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }
}