package com.bs.beststore.vo;

/**
 * 商铺表
 *sid：商铺id、sname：商铺名、sdesc：商铺说明、sgrade：商铺评分、
 *sale：商铺优惠，满a减b，存储格式为：a-b,a-b、hid：商铺创立人信息
 */
public class Store {
    private Integer sid;

    private String sname;

    private String sdesc;

    private Double sgrade;

    private String sale;

    private Integer hid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.SID
     *
     * @return the value of store.SID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.SID
     *
     * @param sid the value for store.SID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.SNAME
     *
     * @return the value of store.SNAME
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.SNAME
     *
     * @param sname the value for store.SNAME
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setSname(String sname) {
        this.sname = sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.SDESC
     *
     * @return the value of store.SDESC
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public String getSdesc() {
        return sdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.SDESC
     *
     * @param sdesc the value for store.SDESC
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setSdesc(String sdesc) {
        this.sdesc = sdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.SGRADE
     *
     * @return the value of store.SGRADE
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Double getSgrade() {
        return sgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.SGRADE
     *
     * @param sgrade the value for store.SGRADE
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setSgrade(Double sgrade) {
        this.sgrade = sgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.SALE
     *
     * @return the value of store.SALE
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public String getSale() {
        return sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.SALE
     *
     * @param sale the value for store.SALE
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setSale(String sale) {
        this.sale = sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.HID
     *
     * @return the value of store.HID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.HID
     *
     * @param hid the value for store.HID
     *
     * @mbg.generated Sat Aug 18 14:43:52 CST 2018
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }
}