package com.bs.beststore.vo;

public class Type {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.TID
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.TPRINAME
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    private String tpriname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.TPARENTID
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    private Integer tparentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.TID
     *
     * @return the value of type.TID
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.TID
     *
     * @param tid the value for type.TID
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.TPRINAME
     *
     * @return the value of type.TPRINAME
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public String getTpriname() {
        return tpriname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.TPRINAME
     *
     * @param tpriname the value for type.TPRINAME
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public void setTpriname(String tpriname) {
        this.tpriname = tpriname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.TPARENTID
     *
     * @return the value of type.TPARENTID
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public Integer getTparentid() {
        return tparentid;
    }

    @Override
	public String toString() {
		return "Type [tid=" + tid + ", tpriname=" + tpriname + ", tparentid=" + tparentid + "]";
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.TPARENTID
     *
     * @param tparentid the value for type.TPARENTID
     *
     * @mbg.generated Fri Aug 24 11:17:55 CST 2018
     */
    public void setTparentid(Integer tparentid) {
        this.tparentid = tparentid;
    }
}