DROP TABLE ordersreturn;
DROP TABLE discuss;
DROP TABLE blog;
DROP TABLE ordersdetail;
DROP TABLE orders;
DROP TABLE favorite;
DROP TABLE cart;
-- DROP TABLE photo;
DROP TABLE GOODS;
DROP TABLE type;
DROP TABLE store;
DROP TABLE address;
DROP TABLE Human;

-- 用户表（包括管理员）
CREATE TABLE Human(
	HID INT PRIMARY KEY AUTO_INCREMENT,-- 用户id
	HNAME VARCHAR(32) NOT NULL UNIQUE,-- 用户名，非空唯一
	HPWD VARCHAR(32) NOT NULL,-- 密码，非空，由用户名加密码组合加密存储到该字段
	HSEX INT,-- 性别，1为男，0为女
	HEIGHT INT,-- 身高，单位cm
	HWEIGHT DOUBLE(4,2),-- 体重，单位为kg
  HBIRTH TIMESTAMP,-- 生日
	HIDCARD BIGINT UNIQUE,-- 身份证号码，非空唯一
	HPHONE BIGINT UNIQUE,-- 注册手机号
	HEMAIL VARCHAR(32) UNIQUE,-- 邮箱地址
	HPHOTO VARCHAR(32),-- 头像图片路径
	HLIMIT INT NOT NULL-- 账号等级，0用户，1店铺，2超级管理员，3删除
);

-- 用户地址表
CREATE TABLE Address(
	AID INT PRIMARY KEY AUTO_INCREMENT,-- 地址id
	APHONE BIGINT NOT NULL,-- 收货人电话
	ACITY VARCHAR(32) NOT NULL,-- 所在地
	ALOCATION VARCHAR(32) NOT NULL,-- 详细地址
	ACONSIGNEE VARCHAR(32) NOT NULL,-- 收货人姓名
	ASTATUS INT NOT NULL,-- 是否是默认收货地址 1为默认，0非默认
	HID INT,-- 用户id
	FOREIGN KEY (HID) REFERENCES Human (HID)
);

-- 商铺表
CREATE TABLE STORE(
	SID INT PRIMARY KEY AUTO_INCREMENT,-- 商铺id
	SNAME VARCHAR(32) NOT NULL UNIQUE,-- 商铺名
	SDESC VARCHAR(50),-- 商铺说明
	SGRADE DOUBLE(5,2),-- 商铺评分
	SSTATUS INT NOT NULL,-- 商铺状态，0为下架，1为正常
	SALE VARCHAR(50),-- 商铺优惠，满a剪b，存储格式为：a-b,a-b
	STIME TIMESTAMP,-- 商铺创立时间
	HID INT,-- 商铺创立人信息
	FOREIGN KEY (HID) REFERENCES Human (HID)
);

-- 商品类别
CREATE TABLE TYPE(
	TID INT PRIMARY KEY AUTO_INCREMENT,-- 类别id
	TPRINAME VARCHAR(32) NOT NULL,-- 商品类别
	TPARENTID INT-- 父类的id（主类别id为null）
);

-- 商品信息表
CREATE TABLE GOODS(
	GID INT PRIMARY KEY AUTO_INCREMENT,-- 商品id
	GNAME VARCHAR(50) NOT NULL,-- 商品名
	GLASTPRICE DOUBLE(7,2),-- 原价
	GNOWPRICE DOUBLE(7,2) NOT NULL,-- 现价
	GDESC VARCHAR(100),-- 商品描述
	GRADE DOUBLE(5,2),-- 商品评分
	GPUBLISH TIMESTAMP,-- 上架时间
	GNUMBER INT,-- 商品库存数
	GPHOTOPIC VARCHAR(32),-- 图片路径
	TID INT,-- 类别id
	SID INT,-- 店铺id
	GSTATUS INT,-- 商品状态，0审核中，1上架中，2审核未通过，3商家下架，4删除
	FOREIGN KEY (TID) REFERENCES TYPE (TID),
	FOREIGN KEY (SID) REFERENCES STORE (SID)
);
-- select *,tid form favorite a 
-- left join goods b on a.gid=b.gid 
-- left join photo c on b.gid=c.gid 
-- left join type t on b.tidwhere a.hid=#{params};


-- 购物车表
CREATE TABLE CART(
	CID INT PRIMARY KEY AUTO_INCREMENT,-- 购物车id
	CNUM INT NOT NULL DEFAULT '1',-- 数量
	GID INT,-- 商品id
	HID INT,-- 购物信息id
	FOREIGN KEY (GID) REFERENCES GOODS (GID),
	FOREIGN KEY (HID) REFERENCES Human (HID)
);


-- 收藏夹
CREATE TABLE FAVORITE(
	FID INT PRIMARY KEY AUTO_INCREMENT,-- 收藏夹id
	FSTATUS INT NOT NULL,-- 状态，0删除，1正常
	GID INT,-- 商品id
	HID INT,-- 用户id
	FOREIGN KEY (GID) REFERENCES GOODS (GID),
	FOREIGN KEY (HID) REFERENCES Human (HID)
);

-- 订单表
CREATE TABLE ORDERS(
	OID INT PRIMARY KEY AUTO_INCREMENT,-- 订单id
	OTIME TIMESTAMP,-- 提交订单时间
	OPAYTIME TIMESTAMP,-- 付款时间
	ODEALTIME TIMESTAMP,-- 成交时间
	OSTATUS INT NOT NULL,-- 付款状态，0待付款，1待发货，2待收货，3待评价，4评价，5移除
	AID INT,-- 地址id
	HID INT,-- 用户id
	OLASTPRICE DOUBLE(7,2),-- 总原价
	ONOWPRICE DOUBLE(7,2) NOT NULL,-- 总现价（优惠后的价格）	
	FOREIGN KEY (HID) REFERENCES Human (HID),
	FOREIGN KEY (AID) REFERENCES Address (AID)
);

-- 订单详情表
CREATE TABLE ORDERSDETAIL(
	ODID INT PRIMARY KEY AUTO_INCREMENT,-- 订单详情id
	ODSTATUS INT NOT NULL DEFAULT 0,-- 订单详情的状态，默认为0未评价，1已评价
	GPRICE DOUBLE(5,2),-- 商品总价格
	OID INT,-- 订单id
	GID INT,-- 商品id
	NUM INT,	-- 商品数量
	FOREIGN KEY (OID) REFERENCES ORDERS (OID),
	FOREIGN KEY (GID) REFERENCES GOODS (GID)
);

-- 博客表
CREATE TABLE BLOG(
	BID INT PRIMARY KEY AUTO_INCREMENT,-- 博客id
	BTITLE VARCHAR(32) NOT NULL,-- 博客标题
	BDESC VARCHAR(200) NOT NULL,-- 博客描述
	BPHOTO VARCHAR(32) NOT NULL,-- 图片路径
	BTIME TIMESTAMP,-- 发布时间
	BSTATUS INT,-- 博客的状态，0审核中，1发布中，2审核未通过，3删除
	SID INT,-- 商铺id
	FOREIGN KEY (SID) REFERENCES STORE (SID)
);


-- 评论表
CREATE TABLE DISCUSS(
	DID INT PRIMARY KEY AUTO_INCREMENT,-- 评价id
	DTIME TIMESTAMP,-- 评价的时间
	DEPICT VARCHAR(100),-- 评价描述
	DRANK INT NOT NULL,-- 评价星级	0好评，1中评，2差评
	DPHOTO VARCHAR(100),-- 图片路径，每张图片中间用，分隔
	DSTATUS INT NOT NULL,-- 评论状态，用于移除评论，0删除，1正常，2匿名
	ODID INT,-- 订单详情的id
	GID INT,-- 商品id
	HID INT,-- 用户id
	FOREIGN KEY (GID) REFERENCES GOODS (GID),
	FOREIGN KEY (HID) REFERENCES Human (HID)
);


-- 退货退款表
CREATE TABLE ORDERSRETURN(
	ORID INT PRIMARY KEY AUTO_INCREMENT,-- 退款订单id
	ORSERVICE INT NOT NULL,-- 服务类型，0仅退款，1退货退款
	ORSTATUS INT NOT NULL,-- 货物状态，0未收到货，1已收到货
	OREASON INT NOT NULL,-- 退款原因，0质量问题，1发错货物，2七天无理由退款，3多拍重拍
	ORDESC VARCHAR(50),-- 退款说明，50字以内的退款原因描述
	ORPHOTO VARCHAR(32),-- 图片地址
	ORTYPE INT NOT NULL,-- 退款进度 0退款中（默认），1已退款（商家同意退款），2移除
	OID INT,-- 订单id
	FOREIGN KEY (OID) REFERENCES orders (OID)
);
ALTER TABLE ORDERSRETURN AUTO_INCREMENT=1000;
commit;



ALTER TABLE Human AUTO_INCREMENT=1000;
ALTER TABLE address AUTO_INCREMENT=1000;
ALTER TABLE store AUTO_INCREMENT=1000;
ALTER TABLE type AUTO_INCREMENT=1000;
ALTER TABLE GOODS AUTO_INCREMENT=1000;
ALTER TABLE cart AUTO_INCREMENT=1000;
ALTER TABLE favorite AUTO_INCREMENT=1000;
ALTER TABLE orders AUTO_INCREMENT=1000;
ALTER TABLE blog AUTO_INCREMENT=1000;
ALTER TABLE discuss AUTO_INCREMENT=1000;

commit;



