package com.bs.beststore.dao;

import com.bs.beststore.vo.Blog;
import com.bs.beststore.vo.BlogExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface BlogMapper {
	
	@Select("select count(*) count from blog\r\n" + 
			"left join store on blog.sid=store.sid\r\n" + 
			"where store.hid=#{hid}")
	List<Map<String, Object>> getCount(@Param("hid") int hid);
	
	@Select("select * from blog where sid=#{sid} limit #{page},#{rows}")
	List<Blog> selectAllBlog(@Param("sid")int sid,@Param("page")int page,@Param("rows")int rows);
	
	@Select("select count(*) from blog where sid=#{sid}")
	long selectBlogCount(@Param("sid")int sid);
	
	@Select("select * from blog where sid=#{sid} and bstatus=#{bstatus} limit #{page},#{rows}")
	List<Blog> selectBlogByBstatus(@Param("sid")int sid,@Param("bstatus")int bstatus,@Param("page")int page,@Param("rows")int rows);
	
	@Select("select count(*) from blog where sid=#{sid} and bstatus=#{bstatus}")
	long selectByBstatusCount(@Param("sid")int sid,@Param("bstatus")int bstatus);
	
	@Insert("insert into blog values(null,#{btitle},#{bdesc},#{bphoto},current_timestamp(6),0,#{sid})")
	int insertBlog(Blog blog);
	
	@Update("update blog set bstatus=#{bstatus} where bid=#{bid}")
	int updateBstatus(Blog blog);
	
	@Select("select * from blog b left join store s on b.sid=s.sid where bstatus=#{bstatus} order by btime desc")
	List<Map<String,Object>> selectBlogShow(Blog blog);
	
	@Select("select * from blog b left join store s on b.sid=s.sid where bstatus=#{bstatus} order by btime desc limit #{page},#{rows}")
	List<Map<String,Object>> selectExamineBlog(@Param("bstatus")int bstatus,@Param("page")int page,@Param("rows")int rows);
	
	@Select("select count(*) from blog b left join store s on b.sid=s.sid where bstatus=#{bstatus}")
	long selectExamineBlogCount(Blog blog);
	
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    long countByExample(BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int deleteByExample(BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int deleteByPrimaryKey(Integer bid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int insert(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int insertSelective(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    List<Blog> selectByExample(BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    Blog selectByPrimaryKey(Integer bid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") Blog record, @Param("example") BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int updateByExample(@Param("record") Blog record, @Param("example") BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int updateByPrimaryKeySelective(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int updateByPrimaryKey(Blog record);
}