package com.bs.beststore.dao;

import com.bs.beststore.vo.Cart;
import com.bs.beststore.vo.CartExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface CartMapper {
	
	@Select("select * from cart c\r\n" + 
			"left join human h on c.hid=h.hid \r\n" + 
			"left join goods g on c.gid=g.gid \r\n" + 
			"left join store s on s.sid=g.sid\r\n" + 
			"where c.hid=#{hid} and s.sstatus=1 and g.gstatus=1 group by c.gid\r\n"
			+ "limit #{page},#{rows}")
	List<Map<String, Object>> selectByHid(@Param("hid")int hid, @Param("page")long page,@Param("rows")int rows);
	
	@Select("select * from cart c\r\n" + 
			"left join human h on c.hid=h.hid \r\n" + 
			"left join goods g on c.gid=g.gid \r\n" + 
			"left join store s on s.sid=g.sid\r\n" + 
			"where c.cid=#{cid} and s.sstatus=1 and g.gstatus=1 group by c.gid\r\n"
			+ "limit #{page},#{rows}")
	List<Map<String, Object>> selectGoodsByCid(@Param("cid")int cid, @Param("page")long page,@Param("rows")int rows);
	
	@Select("select * from cart c\r\n" + 
			"left join goods g on c.gid=g.gid\r\n" + 
			"where c.gid=#{gid} and c.hid=#{hid}")
	List<Map<String,Object>> selectGoodsAndCart(@Param("gid")int gid,@Param("hid")int hid);
	
	@Select("select cid from orders o \r\n" + 
			"left join ordersdetail od on o.oid=od.oid\r\n" + 
			"left join cart c on c.gid=od.gid\r\n" + 
			"where o.oid=#{oid}")
	List<Cart> selectCidByOid(int oid);
	
	@Select("select sum(cnum) from cart where hid=#{hid}")
	long selectCount(int hid);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    long countByExample(CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int deleteByExample(CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int insertSelective(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    List<Cart> selectByExample(CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    Cart selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") Cart record, @Param("example") CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int updateByExample(@Param("record") Cart record, @Param("example") CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int updateByPrimaryKeySelective(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int updateByPrimaryKey(Cart record);

}