package com.bs.beststore.dao;

import com.bs.beststore.vo.Favorite;
import com.bs.beststore.vo.FavoriteExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface FavoriteMapper {
	@Select("select * from favorite f \r\n" + 
			"left join goods g on f.gid=g.gid \r\n" + 
			"left join store s on s.sid=g.sid\r\n" + 
			"left join type t on g.tid=t.tid \r\n" + 
			"where f.hid=#{hid} and fstatus=1 limit #{page},#{rows};")
	List<Map<String, Object>> findByHid(@Param("hid")int hid,@Param("page")int page,@Param("rows")int rows);
	
	@Select("select count(*) from favorite f left join goods g on f.gid=g.gid left join type t on g.tid=t.tid where f.hid=#{hid} and fstatus=1")
	long selectAllTotal(@Param("hid")int hid);
	
	@Select("select count(*) count from favorite where hid=#{hid}")
	List<Map<String, Object>> getCount(@Param("hid")int hid);
	
	@Select("select * from favorite where gid=#{gid} and hid=#{hid}")
	List<Favorite> findByHidAndGid(@Param("hid")int hid,@Param("gid")int gid);
	
	@Update("update favorite set fstatus=#{fstatus} where gid=#{gid} and hid=#{hid}")
	int updateFstatus(Favorite favorite);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    long countByExample(FavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int deleteByExample(FavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int deleteByPrimaryKey(Integer fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int insert(Favorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int insertSelective(Favorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    List<Favorite> selectByExample(FavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    Favorite selectByPrimaryKey(Integer fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") Favorite record, @Param("example") FavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int updateByExample(@Param("record") Favorite record, @Param("example") FavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int updateByPrimaryKeySelective(Favorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int updateByPrimaryKey(Favorite record);

}