package com.bs.beststore.dao;

import com.bs.beststore.vo.Ordersreturn;
import com.bs.beststore.vo.OrdersreturnExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface OrdersreturnMapper {
	
	@Select("select a.orid,a.oid,d.gname,b.odealtime,b.onowprice,ortype from ordersreturn a\r\n" + 
			"left join orders b on a.oid=b.oid\r\n" + 
			"left join ordersdetail c on a.oid=c.oid\r\n" + 
			"left join goods d on c.gid=d.gid group by orid limit #{pageNo},#{pageSize}")
	List<Map<String, Object>> findAllOrdersReturn(@Param("pageNo")int pageNo, @Param("pageSize")int pageSize);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    long countByExample(OrdersreturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int deleteByExample(OrdersreturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int deleteByPrimaryKey(Integer orid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int insert(Ordersreturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int insertSelective(Ordersreturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    List<Ordersreturn> selectByExample(OrdersreturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    Ordersreturn selectByPrimaryKey(Integer orid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") Ordersreturn record, @Param("example") OrdersreturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int updateByExample(@Param("record") Ordersreturn record, @Param("example") OrdersreturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int updateByPrimaryKeySelective(Ordersreturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int updateByPrimaryKey(Ordersreturn record);
}