package com.bs.beststore.dao;

import com.bs.beststore.vo.Ordersreturn;
import com.bs.beststore.vo.OrdersreturnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrdersreturnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    long countByExample(OrdersreturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int deleteByExample(OrdersreturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int deleteByPrimaryKey(Integer orid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int insert(Ordersreturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int insertSelective(Ordersreturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    List<Ordersreturn> selectByExample(OrdersreturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    Ordersreturn selectByPrimaryKey(Integer orid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") Ordersreturn record, @Param("example") OrdersreturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int updateByExample(@Param("record") Ordersreturn record, @Param("example") OrdersreturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int updateByPrimaryKeySelective(Ordersreturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int updateByPrimaryKey(Ordersreturn record);
}