package com.bs.beststore.dao;

import com.bs.beststore.vo.Ordersreturn;
import com.bs.beststore.vo.OrdersreturnExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface OrdersreturnMapper {
	
	@Select("select a.orid,a.oid,d.gname,b.odealtime,b.onowprice,ortype from ordersreturn a\r\n" + 
			"left join orders b on a.oid=b.oid\r\n" + 
			"left join ordersdetail c on a.oid=c.oid\r\n" + 
			"left join goods d on c.gid=d.gid where hid=#{hid} and a.ortype<>2 group by orid limit #{pageNo},#{pageSize}")
	List<Map<String, Object>> findAllOrdersReturn(@Param("hid")int hid, @Param("pageNo")int pageNo, @Param("pageSize")int pageSize);
	
	@Select("select a.orid,a.oid,d.gname,b.odealtime,b.onowprice,ortype from ordersreturn a\r\n" + 
			"left join orders b on a.oid=b.oid\r\n" + 
			"left join ordersdetail c on a.oid=c.oid\r\n" + 
			"left join goods d on c.gid=d.gid where hid=#{hid} and orservice=#{type} and a.ortype<>2 group by orid limit #{pageNo},#{pageSize}")
	List<Map<String, Object>> findAllOrdersReturnByType(@Param("hid")int hid, @Param("type")int type, @Param("pageNo")int pageNo, @Param("pageSize")int pageSize);
	
	@Select("select count(*) count from ordersreturn a\r\n" + 
			"left join orders b on  a.oid=b.oid\r\n" + 
			"where b.hid=#{hid} and a.ortype<>2")
	List<Map<String, Object>> getCountByHid(@Param("hid")int hid);
	
	@Select("select count(*) count from ordersreturn a\r\n" + 
			"left join orders b on  a.oid=b.oid\r\n" + 
			"where b.hid=#{hid} and a.orservice=#{type} and a.ortype<>2")
	List<Map<String, Object>> getCountByType(@Param("hid")int hid, @Param("type")int type);
	
	@Select("select a.*,d.gname,b.odealtime,b.onowprice,gphotopic,hname from ordersreturn a\r\n" + 
			"left join orders b on a.oid=b.oid\r\n" + 
			"left join ordersdetail c on a.oid=c.oid\r\n" + 
			"left join goods d on c.gid=d.gid left join human e on e.hid=b.hid "
			+ "where d.sid=#{sid} group by orid limit #{pageNo},#{pageSize}")
	List<Map<String, Object>> findAllReturnBySid(@Param("sid")int sid, @Param("pageNo")int pageNo, @Param("pageSize")int pageSize);
	
	@Select("select count(distinct orid) from ordersreturn a\r\n" + 
			"left join orders b on a.oid=b.oid\r\n" + 
			"left join ordersdetail c on a.oid=c.oid\r\n" + 
			"left join goods d on c.gid=d.gid left join human e on e.hid=b.hid where d.sid=#{sid}")
	long findAllReturnBySidTotal(@Param("sid")int sid);
	
	@Select("select a.*,d.gname,b.odealtime,b.onowprice,gphotopic,hname from ordersreturn a\r\n" + 
			"left join orders b on a.oid=b.oid\r\n" + 
			"left join ordersdetail c on a.oid=c.oid\r\n" + 
			"left join goods d on c.gid=d.gid left join human e on e.hid=b.hid "
			+ "where d.sid=#{sid} and ortype=#{ortype} group by orid limit #{pageNo},#{pageSize}")
	List<Map<String, Object>> findReturnBySidAndOrtype(@Param("sid")int sid,@Param("ortype")int ortype, @Param("pageNo")int pageNo, @Param("pageSize")int pageSize);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    long countByExample(OrdersreturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int deleteByExample(OrdersreturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int deleteByPrimaryKey(Integer orid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int insert(Ordersreturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int insertSelective(Ordersreturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    List<Ordersreturn> selectByExample(OrdersreturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    Ordersreturn selectByPrimaryKey(Integer orid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") Ordersreturn record, @Param("example") OrdersreturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int updateByExample(@Param("record") Ordersreturn record, @Param("example") OrdersreturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int updateByPrimaryKeySelective(Ordersreturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersreturn
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int updateByPrimaryKey(Ordersreturn record);
}