package com.bs.beststore.dao;

import com.bs.beststore.vo.Store;
import com.bs.beststore.vo.StoreExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface StoreMapper {
	
	@Select("select sid,sname,sgrade,sstatus,stime,sdesc,hname from store s left join human h on s.hid=h.hid where sstatus=#{sstatus} limit #{page},#{rows}")
	List<Map<String,Object>> findAllByStatus(@Param("sstatus")int sstatus,@Param("page")int page,@Param("rows")int rows);
	
	@Select("select sid,sname,sgrade,sstatus,stime,sdesc,hname from store s left join human h on s.hid=h.hid limit #{page},#{rows}")
	List<Map<String,Object>> findAllStoreInfo(@Param("page")int page,@Param("rows")int rows);
	
	@Select("select count(*) from store s left join human h on s.hid=h.hid where sstatus=#{sstatus}")
	long findAllByStatusTotal(Store store);
	
	@Select("select count(*) from store s left join human h on s.hid=h.hid")
	long findAllStoreInfoTotal();
	
	@Update("update store set sstatus=#{sstatus} where sid=#{sid}")
	int updateStoreSstatus(Store store);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    long countByExample(StoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int deleteByExample(StoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int insert(Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int insertSelective(Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    List<Store> selectByExample(StoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    Store selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") Store record, @Param("example") StoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int updateByExample(@Param("record") Store record, @Param("example") StoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int updateByPrimaryKeySelective(Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Wed Aug 29 09:57:28 CST 2018
     */
    int updateByPrimaryKey(Store record);
}