package com.bs.beststore.dao;

import com.bs.beststore.vo.Type;
import com.bs.beststore.vo.TypeExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface TypeMapper {
	@Select("select * from type where tpriname=#{params} or tsecname=#{params}")
	List<Type> findByName(@Param("params")String params);

	@Select("select t3.tpriname name1,t3.tid tid1,t2.tpriname name2,t2.tid tid2,t1.tpriname name3,t1.tid tid3 "
			+ "from type t1 left join type t2 on t1.tparentid=t2.tid left join type t3 on t2.tparentid=t3.tid "
			+ "where t1.tparentid is not null and t2.tparentid is not null;")
	List<Map<String,Object>> selectAllType();

	@Select("select tid tid2,tpriname tname2 from type where tparentid=#{tparentid};")
	List<Map<String,Object>> selectSecondType(@Param("tparentid")int tparentid);

	@Select("select tid tid3,tpriname tname3 from type where tparentid=#{tparentid};")
	List<Map<String,Object>> selectThirdType(@Param("tparentid")int tparentid);

	@Select("select t3.tpriname name1,t3.tid tid1,t2.tpriname name2,t2.tid tid2,t1.tpriname name3,t1.tid tid3,g.* " + 
			"from type t1 left join type t2 on t1.tparentid=t2.tid left join type t3 on t2.tparentid=t3.tid left join goods g on t1.tid=g.tid left join store s on s.sid=g.sid " + 
			"where t1.tparentid is not null and t2.tparentid is not null and gstatus=1 and t3.tid=#{tid} and g.gstatus=1 and s.sstatus=1 order by gpublish desc limit 0,8")
	List<Map<String,Object>> selectTypeToIndex(@Param("tid")int tid);

	//查询以tid为tparentid的类别
	@Select("select tpriname from type where tparentid=#{tparentid};")
	List<String> selectByTparentid(@Param("tparentid")int tparentid);


	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table type
	 *
	 * @mbg.generated Wed Aug 29 09:57:28 CST 2018
	 */
	long countByExample(TypeExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table type
	 *
	 * @mbg.generated Wed Aug 29 09:57:28 CST 2018
	 */
	int deleteByExample(TypeExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table type
	 *
	 * @mbg.generated Wed Aug 29 09:57:28 CST 2018
	 */
	int deleteByPrimaryKey(Integer tid);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table type
	 *
	 * @mbg.generated Wed Aug 29 09:57:28 CST 2018
	 */
	int insert(Type record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table type
	 *
	 * @mbg.generated Wed Aug 29 09:57:28 CST 2018
	 */
	int insertSelective(Type record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table type
	 *
	 * @mbg.generated Wed Aug 29 09:57:28 CST 2018
	 */
	List<Type> selectByExample(TypeExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table type
	 *
	 * @mbg.generated Wed Aug 29 09:57:28 CST 2018
	 */
	Type selectByPrimaryKey(Integer tid);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table type
	 *
	 * @mbg.generated Wed Aug 29 09:57:28 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Type record, @Param("example") TypeExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table type
	 *
	 * @mbg.generated Wed Aug 29 09:57:28 CST 2018
	 */
	int updateByExample(@Param("record") Type record, @Param("example") TypeExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table type
	 *
	 * @mbg.generated Wed Aug 29 09:57:28 CST 2018
	 */
	int updateByPrimaryKeySelective(Type record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table type
	 *
	 * @mbg.generated Wed Aug 29 09:57:28 CST 2018
	 */
	int updateByPrimaryKey(Type record);
}